name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
      
    - name: Run golangci-lint
      # You may pin to the exact commit or the version.
      # uses: golangci/golangci-lint-action@537aa1903e5d359d0b27dbc19ddd22c5087f3fbc
      uses: golangci/golangci-lint-action@v3.2.0
    
    - name: Go Test Action
      # You may pin to the exact commit or the version.
      # uses: robherley/go-test-action@d2be031ae805ef1cfd282b685ff38f8b65e799b8
      uses: robherley/go-test-action@v0.1.0
  
    - name: Go Coverage Badge
      # You may pin to the exact commit or the version.
      # uses: tj-actions/coverage-badge-go@57e0c6b82e0bf6b0d486c4d8df22a51067f26fb7
      uses: tj-actions/coverage-badge-go@v1.2
      
    - name: Go Coverage
      # You may pin to the exact commit or the version.
      # uses: gwatts/go-coverage-action@3c0cc6a187314c587a6369034fc4abf9db0e63ab
      uses: gwatts/go-coverage-action@v1.1.2
